id: A66080550
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
type: translation
pechas:
- IAAD68BAA
- I283A05B5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:34.195268
  last_modified_at: 2023-01-04 12:15:34.195273
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IAAD68BAA/B94F: D5DD
  I283A05B5/B8A0: D5DD
